## Homework 5 - Numerical 

In [4]:
import math
import numpy as np 
import matplotlib.pyplot as plt 
plt.style.use('seaborn')
%matplotlib inline

In [5]:
np.random.seed(0)

In [6]:
# time index for the data 
time_index = np.arange(0.01, 1.01, 0.01)

In [16]:
# time incrementing per each value of t
time_increment = time_index[1:] - time_index[:-1]

Simulate 100 paths for the diffusions below on $[0,1]$ using the Euler scheme (see Chapter 7) for a discretization of $0.01$

In [7]:
# standard brownian motion covariance matrix 
bm_cov = np.reshape(np.array([i if i < j else j for j in time_index for i in time_index]), (100,100))

In [22]:
# the standard brownian motion to be implemented 
brownian_motion = np.insert(np.array([np.linalg.cholesky(bm_cov).dot(np.random.normal(loc=0, 
                                                                                      scale=1, 
                                                                                      size=100)) for _ in range(100)]), 
                            obj=0, 
                            values=0,
                            axis=1)

In [32]:
brownian_increments = np.delete(np.roll(brownian_motion,-1) - brownian_motion, obj=100, axis=1)

In [33]:
brownian_increments

array([[ 0.05559627,  0.08924739, -0.04223148, ..., -0.00654884,
         0.03481692,  0.06632581],
       [-0.11046166, -0.00309363,  0.15788652, ..., -0.05937774,
        -0.20118803,  0.05897036],
       [-0.08963697, -0.1962732 ,  0.15848205, ...,  0.03077326,
         0.01592505, -0.1958549 ],
       ...,
       [ 0.18013814,  0.0493093 ,  0.07483561, ..., -0.08812942,
         0.00249902, -0.03142262],
       [-0.15077643, -0.05018022,  0.1016574 , ...,  0.00616048,
        -0.06883229,  0.06314316],
       [ 0.0214745 , -0.04651605,  0.00913353, ..., -0.01114131,
         0.1018291 ,  0.01798266]])

In [57]:
brownian_increments[0][:4]

array([ 0.05559627,  0.08924739, -0.04223148,  0.0104714 ])

In [59]:
temp = 1
for i in brownian_increments[0][:4]:
    print(temp + (temp * i))
    temp += temp * i

1.0555962679709798
1.1498054784438514
1.1012474886031225
1.1127790947966143


In [61]:
brownian_increments[0][:4].cumprod()

array([ 5.55962680e-02,  4.96182174e-03, -2.09545088e-04, -2.19423105e-06])

b) $dX_t = -X_tdt + dB_t, \ \ X_0 = 1$

c) $dZ_t = 0.5dt + \sqrt{Z_t}dB_t, \ \ Z_0 = 5$

Discard the path if they become negative here. Out of 100, how many paths are discarded?